{
 "title": "Http errors calling Google",
 "time": { "from": "2020-07-30T12:20:20.380Z", "to": "2020-07-30T12:20:36.896Z" },
 "panels": [
  {
   "title": "Successful Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(1) as \"count\" from \"Call\" WHERE $__timeFilter(\"DateTime\") AND \"IsSuccess\" = true\n\n"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(1) as \"count\" from \"Call\" WHERE $__timeFilter(\"DateTime\") AND \"IsSuccess\" = false\n\n"
    }
   ]
  },
  {
   "title": "Requests taking over 5s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(1) as \"count\" from \"Call\" WHERE $__timeFilter(\"DateTime\") AND \"Duration\" > 5\n\n"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"DateTime\" AS \"time\",\n  \"Duration\"\nFROM \"Call\"\nWHERE\n  $__timeFilter(\"DateTime\")\nORDER BY 1,2"
    }
   ]
  }
 ]
}